import Item from '../interfaces/Item';
import virve from './usableItems/virve';
import divainais_burkans from './usableItems/divainais_burkans';
import mugursoma from './usableItems/mugursoma';
import latloto from './usableItems/latloto';
import dizloto from './usableItems/dizloto';
import kafija from './usableItems/kafija';
import kafijas_aparats from './usableItems/kafijas_aparats';
import velo from './usableItems/velo';
import divaina_mugursoma from './usableItems/divaina_mugursoma';
import petnieks from './usableItems/petnieks';
import juridiska_zivs from './usableItems/juridiska_zivs';
import maksekeresData from '../commands/economyCommands/zvejot/makskeresData';
import makskere, { makskereCustomValue } from './usableItems/makskere';
import naudas_maiss from './usableItems/naudas_maiss';
import brivgrieziens from './usableItems/brivgrieziens';
import smilsu_pulkstenis from './usableItems/smilsu_pulkstenis';

export type ItemKey = string;

export enum ItemCategory {
  ATKRITUMI,
  VEIKALS,
  ZIVIS,
  MAKSKERE,
  BRIVGRIEZIENS,
  TIRGUS,
  OTHER,
}

const itemList: Record<ItemKey, Item> = {
  // -- veikals --
  koka_makskere: {
    nameNomVsk: 'koka makšķere',
    nameNomDsk: 'koka makšķeres',
    nameAkuVsk: 'koka makšķeri',
    nameAkuDsk: 'koka makšķeres',
    isVirsiesuDzimte: false,
    emoji: {
      id: '1009557004651601931',
      name: 'kokamakskere',
    },
    imgLink: 'https://i.postimg.cc/wBnfqzy2/kokamakskere.png',
    categories: [ItemCategory.VEIKALS, ItemCategory.MAKSKERE],
    value: 100,
    customValue: makskereCustomValue('koka_makskere'),
    attributes: {
      durability: maksekeresData.koka_makskere.maxDurability,
    },
    allowDiscount: true,
    use: makskere,
  },
  latloto: {
    nameNomVsk: 'latloto biļete',
    nameNomDsk: 'latloto biļetes',
    nameAkuVsk: 'latloto biļeti',
    nameAkuDsk: 'latloto biļetes',
    isVirsiesuDzimte: true,
    emoji: {
      id: '1009557006098645062',
      name: 'latloto',
    },
    imgLink: 'https://i.postimg.cc/SKYdtPTM/latloto.png',
    categories: [ItemCategory.VEIKALS],
    value: 50,
    removedOnUse: true,
    use: latloto,
  },
  nazis: {
    nameNomVsk: 'nazis',
    nameNomDsk: 'naži',
    nameAkuVsk: 'nazi',
    nameAkuDsk: 'nažus',
    isVirsiesuDzimte: true,
    emoji: {
      id: '1009557010305531944',
      name: 'nazis',
    },
    imgLink: 'https://i.postimg.cc/DZqg7XKf/nazis.png',
    categories: [ItemCategory.VEIKALS],
    value: 125,
    removedOnUse: true,
    allowDiscount: true,
    // use() {},
  },
  virve: {
    nameNomVsk: 'virve',
    nameNomDsk: 'virves',
    nameAkuVsk: 'virvi',
    nameAkuDsk: 'virves',
    isVirsiesuDzimte: false,
    emoji: {
      id: '1009557012855652453',
      name: 'virve',
    },
    imgLink: 'https://i.postimg.cc/rmCSB2SK/virve.png',
    categories: [ItemCategory.VEIKALS],
    value: 10,
    allowDiscount: true,
    removedOnUse: true,
    use: virve,
  },
  zemenu_rasens: {
    nameNomVsk: 'zemeņu Rasēns',
    nameNomDsk: 'zemeņu Rasēni',
    nameAkuVsk: 'zemeņu Rasēnu',
    nameAkuDsk: 'zemeņu Rasēnus',
    isVirsiesuDzimte: true,
    emoji: {
      id: '1009557014143324190',
      name: 'zemenu_rasens',
    },
    imgLink: 'https://i.postimg.cc/Vsgq41fh/zemenu-rasens.png',
    categories: [ItemCategory.VEIKALS],
    value: 75,
    allowDiscount: true,
    removedOnUse: true,
    // use() {},
  },
  divainais_burkans: {
    nameNomVsk: 'dīvainais burkāns',
    nameNomDsk: 'dīvainie burkāni',
    nameAkuVsk: 'dīvaino burkānu',
    nameAkuDsk: 'dīvainos burkānus',
    isVirsiesuDzimte: true,
    emoji: {
      id: '1029745787850194994',
      name: 'divainais_burkans',
      animated: true,
    },
    imgLink: 'https://i.postimg.cc/vHRJytjW/divainais-burkans.gif',
    categories: [ItemCategory.VEIKALS],
    value: 5000,
    // eslint-disable-next-line func-names
    customValue: function ({ customName }) {
      // humors
      if (customName!.toLowerCase().includes('seks')) return 6969;

      // pārbauda kirilicu
      if (/[а-яА-ЯЁё]/.test(customName!)) return 0;

      return this.value;
    },
    attributes: {
      timesUsed: 0,
      customName: '',
    },
    allowDiscount: true,
    use: divainais_burkans,
  },
  dizloto: {
    nameNomVsk: 'dižloto biļete',
    nameNomDsk: 'dižloto biļetes',
    nameAkuVsk: 'dižloto biļeti',
    nameAkuDsk: 'dižloto biļetes',
    isVirsiesuDzimte: false,
    emoji: {
      id: '1029738364875837500',
      name: 'dizloto',
      animated: true,
    },
    imgLink: 'https://i.postimg.cc/vZbCgHGT/dizloto.gif',
    categories: [ItemCategory.VEIKALS],
    value: 250,
    removedOnUse: true,
    use: dizloto,
  },
  divaina_makskere: {
    nameNomVsk: 'dīvainā makšķere',
    nameNomDsk: 'dīvainās makšķeres',
    nameAkuVsk: 'dīvaino makšķeri',
    nameAkuDsk: 'dīvainās makšķeres',
    isVirsiesuDzimte: false,
    emoji: {
      id: '1029750421624979548',
      name: 'divaina_makskere',
      animated: true,
    },
    imgLink: 'https://i.postimg.cc/bJ80z0dr/divaina-makskere.gif',
    categories: [ItemCategory.VEIKALS, ItemCategory.MAKSKERE],
    value: 500,
    customValue: makskereCustomValue('divaina_makskere'),
    attributes: {
      durability: maksekeresData.divaina_makskere.maxDurability,
    },
    allowDiscount: true,
    use: makskere,
  },
  mugursoma: {
    nameNomVsk: 'mugursoma',
    nameNomDsk: 'mugursomas',
    nameAkuVsk: 'mugursomu',
    nameAkuDsk: 'mugursomas',
    isVirsiesuDzimte: false,
    emoji: {
      id: '1009557008850092059',
      name: 'mugursoma',
    },
    imgLink: 'https://i.postimg.cc/YChzhVws/mugursoma.png',
    categories: [ItemCategory.VEIKALS],
    value: 500,
    allowDiscount: true,
    removedOnUse: false,
    use: mugursoma,
  },

  // -- tirgus --
  divaina_mugursoma: {
    nameNomVsk: 'dīvainā mugursoma',
    nameNomDsk: 'dīvainās mugursomas',
    nameAkuVsk: 'dīvaino mugursomu',
    nameAkuDsk: 'dīvainās mugursomas',
    isVirsiesuDzimte: false,
    emoji: {
      id: '1029772502542594089',
      name: 'divaina_mugursoma',
      animated: true,
    },
    imgLink: 'https://i.postimg.cc/v8kxDGSf/divaina-mugursoma.gif',
    categories: [ItemCategory.TIRGUS],
    tirgusPrice: { items: { mugursoma: 3 }, lati: 100 },
    value: 1000,
    allowDiscount: true,
    removedOnUse: false,
    use: divaina_mugursoma,
  },
  kafijas_aparats: {
    nameNomVsk: 'kafijas aparāts',
    nameNomDsk: 'kafijas aparāti',
    nameAkuVsk: 'kafijas aparātu',
    nameAkuDsk: 'kafijas aparātus',
    isVirsiesuDzimte: true,
    emoji: {
      id: '1011300411191341139',
      name: 'kafijas_aparats',
    },
    imgLink: 'https://i.postimg.cc/CLwvLm13/kafijas-aparats.png',
    categories: [ItemCategory.TIRGUS],
    value: 100,
    tirgusPrice: { items: { kafija: 15 } },
    attributes: {
      lastUsed: 0,
    },
    removedOnUse: false,
    use: kafijas_aparats,
  },
  petnieks: {
    nameNomVsk: 'pētnieks',
    nameNomDsk: 'pētnieki',
    nameAkuVsk: 'pētnieku',
    nameAkuDsk: 'pētniekus',
    isVirsiesuDzimte: true,
    emoji: {
      id: '1029800146638213160',
      name: 'petnieks',
    },
    imgLink: 'https://i.postimg.cc/D0JW5NmS/petnieks.png',
    categories: [ItemCategory.TIRGUS],
    value: 300,
    tirgusPrice: { items: { brivgriez25: 6, brivgriez50: 4, brivgriez100: 2 }, lati: 500 },
    attributes: {
      lastUsed: 0,
      foundItemKey: '',
    },
    removedOnUse: false,
    use: petnieks,
  },
  loto_makskere: {
    nameNomVsk: 'loto makšķere',
    nameNomDsk: 'loto makšķeres',
    nameAkuVsk: 'loto makšķeri',
    nameAkuDsk: 'loto makšķeres',
    isVirsiesuDzimte: false,
    emoji: {
      id: '1029752905470849105',
      name: 'loto_makskere',
      animated: true,
    },
    imgLink: 'https://i.postimg.cc/pTZfy9nZ/loto-makskere.gif',
    categories: [ItemCategory.TIRGUS, ItemCategory.MAKSKERE],
    value: 200,
    customValue: makskereCustomValue('loto_makskere'),
    tirgusPrice: { items: { latloto: 3, dizloto: 2, brivgriez25: 2, brivgriez50: 1 } },
    attributes: {
      durability: maksekeresData.loto_makskere.maxDurability,
    },
    removedOnUse: false,
    use: makskere,
  },
  luznu_makskere: {
    nameNomVsk: 'lūžņu makšķere',
    nameNomDsk: 'lūžņu makšķeres',
    nameAkuVsk: 'lūžņu makšķeri',
    nameAkuDsk: 'lūžņu makšķeres',
    isVirsiesuDzimte: false,
    emoji: {
      id: '1028069745251057684',
      name: 'luznu_makskere',
    },
    imgLink: 'https://i.postimg.cc/kGsvbP4k/luznu-makskere.png',
    categories: [ItemCategory.TIRGUS, ItemCategory.MAKSKERE],
    value: 100,
    customValue: makskereCustomValue('luznu_makskere'),
    tirgusPrice: { items: { metalluznis: 15 } },
    attributes: {
      durability: maksekeresData.luznu_makskere.maxDurability,
    },
    removedOnUse: false,
    use: makskere,
  },
  naudas_maiss: {
    nameNomVsk: 'naudas maiss',
    nameNomDsk: 'naudas maisi',
    nameAkuVsk: 'naudas maisu',
    nameAkuDsk: 'naudas maisus',
    isVirsiesuDzimte: true,
    emoji: {
      id: '1029800143832240148',
      name: 'naudas_maiss',
    },
    imgLink: 'https://i.postimg.cc/prwmSBnq/naudas-maiss.png',
    categories: [ItemCategory.TIRGUS],
    value: 10,
    // eslint-disable-next-line func-names
    customValue: function ({ latiCollected }) {
      return latiCollected || this.value;
    },
    tirgusPrice: { items: { nazis: 1 } },
    attributes: {
      latiCollected: 0,
    },
    removedOnUse: false,
    use: naudas_maiss,
  },

  // -- atkritumi --
  kartona_kaste: {
    nameNomVsk: 'kartona kaste',
    nameNomDsk: 'kartona kastes',
    nameAkuVsk: 'kartona kasti',
    nameAkuDsk: 'kartona kastes',
    isVirsiesuDzimte: false,
    emoji: {
      id: '1009557002667687958',
      name: 'kartona_kaste',
    },
    imgLink: 'https://i.postimg.cc/WzwXwJ9Y/kartona-kaste.png',
    categories: [ItemCategory.ATKRITUMI],
    value: 15,
  },
  pudele: {
    nameNomVsk: 'stikla pudele',
    nameNomDsk: 'stikla pudeles',
    nameAkuVsk: 'stikla pudeli',
    nameAkuDsk: 'stikla pudeles',
    isVirsiesuDzimte: false,
    emoji: {
      id: '1009557011526074438',
      name: 'pudele',
    },
    imgLink: 'https://i.postimg.cc/L43T7LTN/pudele.png',
    categories: [ItemCategory.ATKRITUMI],
    value: 10,
  },
  metalluznis: {
    nameNomVsk: 'metāllūznis',
    nameNomDsk: 'metāllūžņi',
    nameAkuVsk: 'metāllūzni',
    nameAkuDsk: 'metāllūžņus',
    isVirsiesuDzimte: true,
    emoji: {
      id: '1029732945788932137',
      name: 'metalluznis',
    },
    imgLink: 'https://i.postimg.cc/B6KgnnCY/metalluznis.png',
    categories: [ItemCategory.ATKRITUMI],
    value: 10,
  },

  // -- zivis --
  lidaka: {
    nameNomVsk: 'līdaka',
    nameNomDsk: 'līdakas',
    nameAkuVsk: 'līdaku',
    nameAkuDsk: 'līdakas',
    isVirsiesuDzimte: false,
    emoji: {
      id: '1028069743988588586',
      name: 'lidaka',
    },
    imgLink: 'https://i.postimg.cc/4N45Ty2Z/lidaka.png',
    categories: [ItemCategory.ZIVIS],
    value: 10,
  },
  asaris: {
    nameNomVsk: 'asaris',
    nameNomDsk: 'asari',
    nameAkuVsk: 'asari',
    nameAkuDsk: 'asarus',
    isVirsiesuDzimte: true,
    emoji: {
      id: '1028069739890757753',
      name: 'asaris',
    },
    imgLink: 'https://i.postimg.cc/VvmFvkYq/asaris.png',
    categories: [ItemCategory.ZIVIS],
    value: 15,
  },
  lasis: {
    nameNomVsk: 'lasis',
    nameNomDsk: 'laši',
    nameAkuVsk: 'lasi',
    nameAkuDsk: 'lašus',
    isVirsiesuDzimte: true,
    emoji: {
      id: '1028069742558314526',
      name: 'lasis',
    },
    imgLink: 'https://i.postimg.cc/yYnLJc3k/lasis.png',
    categories: [ItemCategory.ZIVIS],
    value: 20,
  },
  // loto_zivs: {
  //   nameNomVsk: 'loto zivs',
  //   nameNomDsk: 'loto zivis',
  //   nameAkuVsk: 'loto zivi',
  //   nameAkuDsk: 'loto zivis',
  //   isVirsiesuDzimte: false,
  //   emoji: null,
  //   categories: [ItemCategory.ZIVIS],
  //   value: 50,
  // },
  juridiska_zivs: {
    nameNomVsk: 'juridiskā zivs',
    nameNomDsk: 'juridiskās zivis',
    nameAkuVsk: 'juridisko zivi',
    nameAkuDsk: 'juridiskās zivis',
    isVirsiesuDzimte: false,
    emoji: {
      id: '1028069741287440486',
      name: 'juridiska_zivs',
    },
    imgLink: 'https://i.postimg.cc/g2QqRDzk/juridiska-zivs.png',
    categories: [ItemCategory.ZIVIS],
    value: 50,
    removedOnUse: true,
    use: juridiska_zivs,
  },
  divaina_zivs: {
    nameNomVsk: 'dīvainā zivs',
    nameNomDsk: 'dīvainās zivis',
    nameAkuVsk: 'dīvano zivi',
    nameAkuDsk: 'dīvainās zivis',
    isVirsiesuDzimte: false,
    emoji: {
      id: '1029789643073388585',
      name: 'divaina_zivs',
      animated: true,
    },
    imgLink: 'https://i.postimg.cc/2SfqF2Y5/divaina-zivs.gif',
    categories: [ItemCategory.ZIVIS],
    value: 50,
    removedOnUse: false,
  },

  // -- velosipēds --
  velosipeds: {
    nameNomVsk: 'velosipēds',
    nameNomDsk: 'velosipēdi',
    nameAkuVsk: 'velosipēdu',
    nameAkuDsk: 'velosipēdus',
    isVirsiesuDzimte: true,
    emoji: {
      id: '1028069751563489320',
      name: 'velosipeds',
    },
    imgLink: 'https://i.postimg.cc/sxT52PHz/velosipeds.png',
    categories: [ItemCategory.OTHER],
    value: 250,
  },
  velo_ramis: {
    nameNomVsk: 'velosipēda rāmis',
    nameNomDsk: 'velosipēda rāmji',
    nameAkuVsk: 'velosipēda rāmi',
    nameAkuDsk: 'velosipēda rāmjus',
    isVirsiesuDzimte: true,
    emoji: {
      id: '1028069747297894512',
      name: 'velo_ramis',
    },
    imgLink: 'https://i.postimg.cc/DyCcfhRG/velo-ramis.png',
    categories: [ItemCategory.OTHER],
    value: 10,
    use: velo,
  },
  velo_ritenis: {
    nameNomVsk: 'velosipēda ritenis',
    nameNomDsk: 'velosipēda riteņi',
    nameAkuVsk: 'velosipēda riteni',
    nameAkuDsk: 'velosipēda riteņus',
    isVirsiesuDzimte: true,
    emoji: {
      id: '1028069749038534766',
      name: 'velo_ritenis',
    },
    imgLink: 'https://i.postimg.cc/zvzn52jp/velo-ritenis.png',
    categories: [ItemCategory.OTHER],
    value: 10,
    use: velo,
  },
  velo_kede: {
    nameNomVsk: 'velosipēda ķēde',
    nameNomDsk: 'velosipēda ķēdes',
    nameAkuVsk: 'velosipēda ķēdi',
    nameAkuDsk: 'velosipēda ķēdes',
    isVirsiesuDzimte: false,
    emoji: {
      id: '1028069746509348904',
      name: 'velo_kede',
    },
    imgLink: 'https://i.postimg.cc/JnWNYzHf/velo-kede.png',
    categories: [ItemCategory.OTHER],
    value: 10,
    use: velo,
  },
  velo_sture: {
    nameNomVsk: 'velosipēda stūre',
    nameNomDsk: 'velosipēda stūres',
    nameAkuVsk: 'velosipēda stūri',
    nameAkuDsk: 'velosipēda stūres',
    isVirsiesuDzimte: false,
    emoji: {
      id: '1028069750317789224',
      name: 'velo_sture',
    },
    imgLink: 'https://i.postimg.cc/tg6dzxJd/velo-sture.png',
    categories: [ItemCategory.OTHER],
    value: 10,
    use: velo,
  },

  // -- citas mantas --
  kafija: {
    nameNomVsk: 'kafija',
    nameNomDsk: 'kafijas',
    nameAkuVsk: 'kafiju',
    nameAkuDsk: 'kafijas',
    isVirsiesuDzimte: false,
    emoji: {
      id: '1009557001451356161',
      name: 'kafija',
    },
    imgLink: 'https://i.postimg.cc/SQ6ThwyL/kafija.png',
    categories: [ItemCategory.OTHER],
    value: 50,
    allowDiscount: true,
    removedOnUse: false,
    use: kafija,
  },
  dizmakskere: {
    nameNomVsk: 'dižmakšķere',
    nameNomDsk: 'dižmakšķeres',
    nameAkuVsk: 'dižmakšķeri',
    nameAkuDsk: 'dižmakšķeres',
    isVirsiesuDzimte: false,
    emoji: {
      id: '1029758877752897569',
      name: 'dizmakskere',
      animated: true,
    },
    imgLink: 'https://i.postimg.cc/Xq55MQ0p/dizmakskere.gif',
    categories: [ItemCategory.MAKSKERE],
    value: 500,
    customValue: makskereCustomValue('dizmakskere'),
    attributes: {
      durability: maksekeresData.dizmakskere.maxDurability,
    },
    use: makskere,
  },
  smilsu_pulkstenis: {
    nameNomVsk: 'smilšu pulkstenis',
    nameNomDsk: 'smilšu pulksteņi',
    nameAkuVsk: 'smilšu pulksteni',
    nameAkuDsk: 'smilšu pulksteņus',
    isVirsiesuDzimte: true,
    emoji: {
      id: '1029770674056745062',
      name: 'smilsu_pulkstenis',
      animated: true,
    },
    imgLink: 'https://i.postimg.cc/LX0YtS4d/smilsu-pulkstenis.gif',
    categories: [ItemCategory.OTHER],
    value: 100,
    removedOnUse: false,
    use: smilsu_pulkstenis,
  },

  // -- brīvgriezieni --
  brivgriez10: {
    nameNomVsk: '10 latu brīvgrieziens',
    nameNomDsk: '10 latu brīvgriezieni',
    nameAkuVsk: '10 latu brīvgriezienu',
    nameAkuDsk: '10 latu brīvgriezienus',
    isVirsiesuDzimte: true,
    emoji: {
      id: '1029728226571993088',
      name: 'brivgriez10',
    },
    imgLink: 'https://i.postimg.cc/SxgVZ5sr/brivgriez10.png',
    categories: [ItemCategory.BRIVGRIEZIENS],
    value: 2,
    removedOnUse: false,
    use: brivgrieziens(10),
  },
  brivgriez25: {
    nameNomVsk: '25 latu brīvgrieziens',
    nameNomDsk: '25 latu brīvgriezieni',
    nameAkuVsk: '25 latu brīvgriezienu',
    nameAkuDsk: '25 latu brīvgriezienus',
    isVirsiesuDzimte: true,
    emoji: {
      id: '1029729516584701982',
      name: 'brivgriez25',
    },
    imgLink: 'https://i.postimg.cc/d0D6gBZK/brivgriez25.png',
    categories: [ItemCategory.BRIVGRIEZIENS],
    value: 5,
    removedOnUse: false,
    use: brivgrieziens(25),
  },
  brivgriez50: {
    nameNomVsk: '50 latu brīvgrieziens',
    nameNomDsk: '50 latu brīvgriezieni',
    nameAkuVsk: '50 latu brīvgriezienu',
    nameAkuDsk: '50 latu brīvgriezienus',
    isVirsiesuDzimte: true,
    emoji: {
      id: '1029730465189482577',
      name: 'brivgriez50',
    },
    imgLink: 'https://i.postimg.cc/1X1Kn1C9/brivgriez50.png',
    categories: [ItemCategory.BRIVGRIEZIENS],
    value: 10,
    removedOnUse: false,
    use: brivgrieziens(50),
  },
  brivgriez100: {
    nameNomVsk: '100 latu brīvgrieziens',
    nameNomDsk: '100 latu brīvgriezieni',
    nameAkuVsk: '100 latu brīvgriezienu',
    nameAkuDsk: '100 latu brīvgriezienus',
    isVirsiesuDzimte: true,
    emoji: {
      id: '1029731216968122378',
      name: 'brivgriez100',
    },
    imgLink: 'https://i.postimg.cc/R08dmHwJ/brivgriez100.png',
    categories: [ItemCategory.BRIVGRIEZIENS],
    value: 20,
    removedOnUse: false,
    use: brivgrieziens(100),
  },
};

export default itemList;
